# Streamlit secrets
# Add your secrets here, e.g.:
# [openai]
 OPENAI_API_KEY = "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"
#
# See https://docs.streamlit.io/library/advanced-features/secrets for details.
